/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;
import Atxy2k.CustomTextField.RestrictedTextField;
import controller.ClienteDAO;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
/*
 *
 * @author Pedro
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        
        RestrictedTextField validarCliente;
        validarCliente = new RestrictedTextField(Jtxtnome);
        validarCliente.setLimit(50);
        RestrictedTextField validarEndereco;
        validarEndereco = new RestrictedTextField(Jtxtendereco);
        validarEndereco.setLimit(100);
        RestrictedTextField validarFone;
        validarFone = new RestrictedTextField(Jtxttelefone);
        validarFone.setLimit(15);
        RestrictedTextField validarEmail;
        validarEmail = new RestrictedTextField(Jtxtemail);
        validarEmail.setLimit(50);
        
    }
      public void listarClientes(){
        ClienteDAO dao = new ClienteDAO();
        
        List<Cliente> lista = dao.listarClientes();
        DefaultTableModel dados = (DefaultTableModel) Jtxtclientes.getModel();
        dados.setNumRows(0);
        
        for(Cliente c: lista){
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEndereco(),
                c.getTelefone(),
                c.getEmail()
        });
        
        }
        
    }
    private void setarCampos() {
        int setar = Jtxtclientes.getSelectedRow();
        Jtxtidclientes.setText(Jtxtclientes.getModel().getValueAt(setar, 0).toString());
        Jtxtnome.setText(Jtxtclientes.getModel().getValueAt(setar, 1).toString());
        Jtxtendereco.setText(Jtxtclientes.getModel().getValueAt(setar, 2).toString());
        Jtxttelefone.setText(Jtxtclientes.getModel().getValueAt(setar, 3).toString());
        if (Jtxtclientes.getModel().getValueAt(setar, 4) == null){
            Jtxtemail.setText(null);
        } else {
            Jtxtemail.setText(Jtxtclientes.getModel().getValueAt(setar, 4).toString());
        }        
        jBtnAdicionar.setEnabled(false);
        jBtnAlterar.setEnabled(true);
        jBtnRemover.setEnabled(true);
    }

    
      private void limpar() {
        Jtxtpesquisa.setText(null);
        Jtxtidclientes.setText(null);
        Jtxtnome.setText(null);
        Jtxtendereco.setText(null);
        Jtxttelefone.setText(null);
        Jtxtemail.setText(null);
        ((DefaultTableModel) Jtxtclientes.getModel()).setRowCount(0);
        jBtnAdicionar.setEnabled(true);
        jBtnAlterar.setEnabled(false);
        jBtnRemover.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jtxtpesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Jpesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtxtclientes = new javax.swing.JTable();
        Jtxtidclientes = new javax.swing.JTextField();
        Jtxtnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jtxtendereco = new javax.swing.JTextField();
        Jtxttelefone = new javax.swing.JTextField();
        Jtxtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(640, 480));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        Jtxtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtxtpesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtxtpesquisaKeyReleased(evt);
            }
        });

        jLabel1.setText("*Campos Obrigatorios");

        Jpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pesquisar.png"))); // NOI18N

        Jtxtclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "ENDEREÇO", "FONE", "E-MAIL"
            }
        ));
        Jtxtclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtxtclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtxtclientes);

        Jtxtidclientes.setEnabled(false);

        jLabel2.setText("ID Cliente:");

        jLabel3.setText("*Nome:");

        jLabel4.setText("Endereço:");

        jLabel5.setText("*Telefone:");

        jLabel6.setText("E-mail:");

        jBtnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/create.png"))); // NOI18N
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        jBtnAlterar.setEnabled(false);
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jBtnRemover.setEnabled(false);
        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtxtnome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jtxtendereco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtxtidclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtxttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Jtxtemail)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Jtxtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jBtnAdicionar)
                .addGap(75, 75, 75)
                .addComponent(jBtnAlterar)
                .addGap(73, 73, 73)
                .addComponent(jBtnRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtxtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jpesquisar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtidclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdicionar)
                    .addComponent(jBtnRemover)
                    .addComponent(jBtnAlterar))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        try {
            if ((Jtxtnome.getText().isEmpty()) || (Jtxttelefone.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
            } else {
                Cliente obj = new Cliente();
                obj.setNome(Jtxtnome.getText());
                obj.setEndereco(Jtxtendereco.getText());
                obj.setTelefone(Jtxttelefone.getText());
                obj.setEmail(Jtxtemail.getText());

                ClienteDAO dao = new ClienteDAO();
                dao.cadastrarUsuario(obj);
                limpar();
            }
        }catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        listarClientes();
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void JtxtclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtxtclientesMouseClicked
      
        setarCampos();
        
    }//GEN-LAST:event_JtxtclientesMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated

    private void JtxtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtpesquisaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtpesquisaKeyPressed

    private void JtxtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtpesquisaKeyReleased
      
        String pesquisa = Jtxtpesquisa.getText()+"%";
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> lista = new ArrayList();
            lista = dao.consultarClientes(pesquisa);
        DefaultTableModel dados = (DefaultTableModel) Jtxtclientes.getModel();
        dados.setRowCount(0);
        for(Cliente c: lista){
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEndereco(),
                c.getTelefone(),
                c.getEmail()
            
        });
        }
        
    }//GEN-LAST:event_JtxtpesquisaKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    listarClientes();    

    }//GEN-LAST:event_formInternalFrameOpened

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
                                           
        int confirma = JOptionPane.showConfirmDialog(null, "Confima as alterações nos dados deste cliente?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            
            try {
                Cliente obj = new Cliente();
                obj.setNome(Jtxtnome.getText());
                obj.setEndereco(Jtxtendereco.getText());
                obj.setTelefone(Jtxttelefone.getText());
                if (Jtxtemail.getText().equals("")) {
                obj.setEmail(null);
            } else {
                obj.setEmail(Jtxtemail.getText());
            }
                obj.setId(Integer.parseInt(Jtxtidclientes.getText()));
                if ((Jtxtnome.getText().isEmpty()) || (Jtxttelefone.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
                } else {
                    ClienteDAO dao = new ClienteDAO();
                    dao.editarCliente(obj);
                    limpar();
                    listarClientes();
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            } 
        }
    
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverActionPerformed

        int confirma = JOptionPane.showConfirmDialog(null, "Confima a exclusão deste cliente?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            Cliente obj = new Cliente();
            obj.setId(Integer.parseInt(Jtxtidclientes.getText()));
            ClienteDAO dao = new ClienteDAO();
            dao.excluirCliente(obj);
            limpar();
            listarClientes();
        }
        
    }//GEN-LAST:event_jBtnRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jpesquisar;
    private javax.swing.JTable Jtxtclientes;
    private javax.swing.JTextField Jtxtemail;
    private javax.swing.JTextField Jtxtendereco;
    private javax.swing.JTextField Jtxtidclientes;
    private javax.swing.JTextField Jtxtnome;
    private javax.swing.JTextField Jtxtpesquisa;
    private javax.swing.JTextField Jtxttelefone;
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
